apiVersion: v1
kind: List
metadata:
  name: recreate-example
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: upsilon-node
  spec:
    ports:
    - port: 4000
      targetPort: 4000
    selector:
      deploymentconfig: upsilon-node
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: upsilon-node
  spec:
    replicas: 1
    selector:
      deploymentconfig: upsilon-node
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: upsilon-node
      spec:
        containers:
        - image: upsilon-project/node:latest
          name: upsilon-node
          ports:
          - containerPort: 4000
            protocol: TCP
          env:
          - name: UPSILON_CONFIG_SYSTEM_AMQPHOST
            value: upsilon
          - name: UPSILON_IDENTIFIER
            value: unnamed-upsilon-node 
          livenessProbe:
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - upsilon-node
        from:
          kind: ImageStreamTag
          name: upsilon-node:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: upsilon-node
  spec:
    dockerImageRepository: upsilonproject/node
- apiVersion: v1
  kind: Route
  metadata:
    name: upsilon-node
  spec:
    to:
      kind: Service
      name: upsilon-node
